config/routes.rb
Srsguild::Application.routes.draw do
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'signup' => 'accounts#new', :as => :signup

  resources :sessions
  namespace :backend, :conditions => { :subdomain => 'admin' } do
    resource :dashboard

    match '' => 'backend/dashboards#show', :as => :backend_root, :via => :get
  end

  namespace :admin do
    resource :dashboard
    resources :events do
      collection do
        post :char_attendance_row
      end

      member do
        put :update_attendance
      end

      resource :plan do
        member do
          get :stats
        end
      end
    end

    resources :plans, :only => [:index]
    resources :balances do
      member do
        post :filter
      end
    end

    resources :roster, :only => [:index] do
      collection do
        put :update_all
      end

      member do
        put :gkick
        get :create_sms
        put :send_sms
      end
    end

    resources :settings, :only => [:index] do
      collection do
        put :update_all
      end
    end
  end

  resource :guild do
    collection do
      get :_armory_sync_status
      put :_acknowledge_armory_sync_complete
    end
  end

  resources :events, :only => [:index, :show] do
    collection do
      get :attendance
    end

    resource :signup, :only => [:create, :update, :destroy] do
      member do
        put :toggle
      end
    end

    resource :plan, :only => [:show]
  end

  resources :balances do
    member do
      post :filter
    end

    match 'balances/:balance_id/history/:char_id' => 'balances#history', :as => :balance_history, :via => :get
  end

  resources :roster, :only => [:index, :show] do
    collection do
      post :filter
    end
  end

  resource :account do
    member do
      get :success
      get :confirm
      put :resend_confirmation
      get :verify
      put :verify_manual
      get :forgot
      post :remind
      get :new_password
      put :reset_password
    end

    resources :characters, :only => [:index, :new, :create, :destroy, :update] do
      member do
        post :join
        get :find_guild
        post :find_guild
        get :withdraw
        get :armory_update
        get :promote
      end
    end
  end

  match '/account/new_password/:reset_code' => 'accounts#new_password'


  #match '/api/:controller/:action/:id' => '#index', :api => true
  #match '/api/wow/realms.:format' => '/api/wow#realms', :via => :get
  #match '/api/wow/realms/:region.:format' => '/api/wow#realms', :via => :get
  #match '/api/wow/realms/:region/:subregion.:format' => '/api/wow#realms', :via => :get
  #match '/api/wow/realms/:region/:subregion/:realm_type.:format' => '/api/wow#realms', :via => :get

  #match '' => 'guilds#show', :as => :guild_root, :via =>

  match '/' => 'home#index', as: :root
  match 'contact' => 'home#contact', :as => :contact
  match 'security' => 'home#security', :as => :security
  match 'tour' => 'home#tour', :as => :tour
  match 'pricing' => 'home#pricing', :as => :pricing

  match '/:controller(/:action(/:id))'
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController

  def index
    @this_week = @_GUILD.calendar_events.find(:all, :conditions => CalendarEvent.conditions_for_raid_week(Date.today), :order => "begins_at ASC")
    @future_events = @_GUILD.calendar_events.find(:all, :conditions => ["begins_at > ?", CalendarEvent.end_of_raid_week(Date.today) - Time.new.gmt_offset], :order => "begins_at ASC")
    @recent_events = @_GUILD.calendar_events.find(:all, :conditions => "begins_at < UTC_TIMESTAMP()", :order => "begins_at DESC", :limit => 5)
    
    @current_event = @_GUILD.calendar_events.find(:first, :conditions => ["begins_at < ?", Time.new], :order => "begins_at DESC")
    @new_attendance = CalendarEventAttendance.new
    
    @event = CalendarEvent.new
    @event.start_time = @_GUILD.guild_config.c_default_start_time if @_GUILD.guild_config.c_default_start_time
  end
  
  def show
    @event = @_GUILD.calendar_events.find(params[:id])

    @prev_event = @_GUILD.calendar_events.find(:first, :conditions => ["begins_at < ?", @event.begins_at], :order => "begins_at DESC")
    @next_event = @_GUILD.calendar_events.find(:first, :conditions => ["begins_at > ?", @event.begins_at], :order => "begins_at ASC")
  end
  
  def create
    @new_event = CalendarEvent.new(params[:event])
    @new_event.start_time = "#{params[:event]['start_time(4i)']}:#{params[:event]['start_time(5i)']}" # Ergh.
    @new_event.organizer = @_GUILD.characters.find(params[:event][:organizer])
    @new_event.guild = @_GUILD

    if @new_event.save
      flash[:notice] = "New event created successfully."
    else
      flash[:error] = "Unable to create new event."
    end

    redirect_to :action => 'index' and return
  end
  
  def edit
    @event = @_GUILD.calendar_events.find(params[:id])
  end
  
  def update
    event = @_GUILD.calendar_events.find(params[:id])
    
    event.attributes = params[:event]
    event.start_time = "#{params[:event]['start_time(4i)']}:#{params[:event]['start_time(5i)']}" # Ergh.
    event.organizer = @_GUILD.characters.find(params[:event][:organizer])

    if event.save
      flash[:notice] = "Event details updated successfully."
    else
      flash[:error] = "Unable to update event details."
    end
    
    redirect_to :action => 'show', :id => event and return
  end
  
  def update_attendance
    event = @_GUILD.calendar_events.find(params[:id])
    
    event.calendar_event_attendances.clear
    
    unless params[:attendance].blank?
      params[:attendance].each do |char_id, att|
        char = @_GUILD.characters.find(att['id'].to_i)
      
        new_att = CalendarEventAttendance.new
        new_att.character = char
        new_att.calendar_event = event
        new_att.comments = att['notes']
      
        new_att.save!
      end
    end
    
    flash[:notice] = "Event attendance updated."
    redirect_to :action => 'show', :id => event.id and return
  end
  
  def destroy
    event = @_GUILD.calendar_events.find(params[:id])
    
    if event.begins_at > Time.new
      event.destroy
    else
      event.is_deleted = true
      event.save!
    end
    
    flash[:notice] = "Event deleted."
    redirect_to admin_events_url and return
  end
  
  # AJAX methods
  # --------------------------------------------------------------------------
  
  def char_attendance_row
    @char = @_GUILD.main_characters.find_by_name(params[:character_name])
    #@char = Character.find_by_name(params[:character_name])
    @count = params[:count].to_i || ""

    if @char.nil?
      render :text => "Not found.", :status => :forbidden, :layout => false and return
    end
    
    exclude = JSON.parse(params[:exclude])
    
    if exclude.any? { |id| id.to_i == @char.id }
      render :text => "That person is already on the list!", :status => :forbidden, :layout => false and return
    end
    
    render :partial => 'char_attendance_row', :layout => false
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  before_filter :require_login
  before_filter :require_guild
  
  def index
    @this_week = @_GUILD.calendar_events.find(:all, :conditions => CalendarEvent.conditions_for_raid_week(Date.today), :order => "begins_at ASC")
    @next_week = @_GUILD.calendar_events.find(:all, :conditions => CalendarEvent.conditions_for_raid_week(Date.today + 7), :order => "begins_at ASC")
    @past_events = @_GUILD.calendar_events.find(:all, :conditions => ["begins_at < ?", Time.new], :order => "begins_at DESC", :limit => 10, :include => :calendar_event_attendances)
  end
  
  def show
    @event = @_GUILD.calendar_events.find(params[:id])
    redirect_to :action => 'index' and return if @event.nil?
    
    @prev_event = @_GUILD.calendar_events.find(:first, :conditions => ["begins_at < ?", @event.begins_at], :order => "begins_at DESC")
    @next_event = @_GUILD.calendar_events.find(:first, :conditions => ["begins_at > ?", @event.begins_at], :order => "begins_at ASC")
    
    @plan_group_slots = Array.new

    (0..7).each do |i|
      @plan_group_slots[i] = Array.new
    end
    
    @event.event_plan_slots.find(:all, :order => 'group_position ASC').each do |s|
      @plan_group_slots[((s.group_position.to_f-1.0)/5.0).floor.to_i].push(s)
    end
    
    @personal_signup = @_MAIN_CHAR.calendar_event_signups.find(:first, :conditions => ["calendar_event_id = ?", @event.id])
  end

  def attendance
    @events = CalendarEvent.paginate :page => params[:page], :order => 'begins_at DESC', :per_page => 20, :conditions => ["guild_id = ? AND begins_at < ?", @_GUILD.id, Time.new], :include => :calendar_event_attendances
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper

  def admin_calendar_event_link(event)
    return link_to(event.begins_at.strftime("%H:%M"), admin_event_url(event), :title => event.title)
  end
end

app/helpers/events_helper.rb
module EventsHelper

  def calendar_event_link(event)
    "<a href=\"#\" id=\"event_link_#{event.id}\" onclick=\"return false;\">#{event.begins_at.strftime("%H:%M")}</a>\n"
  end
  
  def calendar_signup_role_options
    [
      ['', ''],
      ['Tank', 'tank'],
      ['Healer', 'healer'],
      ['Melee DPS', 'melee_dps'],
      ['Ranged DPS', 'range_dps']
    ]
  end
  
  def printable_role_preference(pref)
    return case pref
      when 'tank' then "Tank"
      when 'healer' then "Healer"
      when 'melee_dps' then "Melee DPS"
      when 'range_dps' then "Ranged DPS"
      else "--"
    end
  end
  
  def p_truncated_at(str, len)
    if str.blank?
			return "<p>--</p>"
		else
			if str.length > len
				"<p title=\"#{html_escape(str)}\">#{html_escape(str[0,len])}...</p>"
			else
				"<p>#{html_escape(str)}</p>"
			end
		end
  end
  
  def show_signups_link(str)
		return link_to_function(str, nil) do |page|
	    page[:calendar_all_signups].show
	    page[:event_past_notice].hide
	  end
  end
end

app/views/admin/events/_attendance_edit.html.erb
<% form_tag(update_attendance_admin_event_url(event), :method => :put) do %>
	<table class="attendlist">
		<tr>
			<th style="width: 20px;"></th>
			<th style="width: 200px;">Name</th>
			<th style="width: 125px;">Class</th>
			<th>Notes</th>
			<th></th>
		</tr>

		<% if event.calendar_event_attendances.blank? %>
			<% event.characters_signed_up.find(:all, :order => 'name ASC').each_with_index do |char, count| %>
				<tr class="attendance_row">
					<td style="text-align: center;"><a href="#" style="color: red; text-decoration: none;" onclick="dropRow(this.up(1)); return false;">X</a></td>
					<td><%=h char.name %><%= hidden_field_tag("attendance[#{char.id}][id]", char.id, {:class => 'char_id'}) %></td>
					<td><%=h char.character_class %></td>
					<td><%= text_field_tag("attendance[#{char.id}][notes]", nil, { :style => "width: 100%;", :class => 'text' }) %></td>
					<td style="color: #ccc; text-align: right; font-weight: bold;"><%= count+1 %></td>
				</tr>
			<% end %>
		<% else %>
			<% event.calendar_event_attendances.find(:all, :include => :character, :order => 'characters.name ASC').each_with_index do |att, count| %>
				<tr class="attendance_row">
					<td style="text-align: center;"><a href="#" style="color: red; text-decoration: none;" onclick="dropRow(this.up(1)); return false;">X</a></td>
					<td><%=h att.character.name %><%= hidden_field_tag("attendance[#{att.character.id}][id]", att.character.id, {:class => 'char_id'}) %></td>
					<td><%=h att.character.character_class %></td>
					<td><%= text_field_tag("attendance[#{att.character.id}][notes]", att.comments, { :style => "width: 100%;", :class => 'text' }) %></td>
					<td style="color: #ccc; text-align: right; font-weight: bold;"><%= count+1 %></td>
				</tr>
			<% end %>
		<% end %>
	
		<tr class="new_attendance">
			<td style="text-align: center;">+</td>
			<td>
				<input type="text" class="text" id="new_attendance_character_name" style="width: 95%;" />
				<div id="new_attendance_character_name_choices" class="auto_complete"></div>
			</td>
			<td colspan="3"><span id="new_attendance_response"></span></td>
		</tr>
	</table>
	
	<% center_buttons do %>
		<button type="submit" class="button positive">
			<%= image_tag('icons/tick.png') %> save attendance
		</button>
	<% end %>
<% end %>

<script type="text/javascript" charset="utf-8">
	$('new_attendance_character_name').observe('keypress', function(event) {
		$('new_attendance_response').innerHTML = "";
		
		var key = event.which || event.keyCode;

		if (key == Event.KEY_RETURN) {
			exclude_ids = new Array;
			
			$$(".attendance_row .char_id").each(function(character, idx) {
				exclude_ids.push(character.value);
			});
			
			new Ajax.Updater({ success: this.up(1) }, "<%= char_attendance_row_admin_events_url %>", {
				parameters: { character_name: this.value, count: $$(".attendance_row").length+1, exclude: exclude_ids.toJSON() },
				insertion: 'before',
				
				onSuccess: function(resp) {
					$('new_attendance_character_name').value = '';
				},
				
				on403: function(resp) {
					$('new_attendance_response').innerHTML = resp.responseText;
					new Effect.Highlight($('new_attendance_response'));
				},

				onFailure: function(resp) {
					$('new_attendance_response').innerHTML = "The system is down yo. Try again in a second.";
					new Effect.Highlight($('new_attendance_response'));
				}
			});
			
			event.stop();
		}
	});
	
	// Auto complete
	new Ajax.Autocompleter("new_attendance_character_name", "new_attendance_character_name_choices", "<%= admin_roster_index_url %>", {callback:function(element, value) { return 'search=' + element.value }, method:'get'});
	
	function dropRow(row) {
		row.remove();
	}
</script>

app/views/admin/events/_char_attendance_row.html.erb
<tr class="attendance_row">
	<td style="text-align: center;"><a href="#" style="color: red; text-decoration: none;" onclick="dropRow(this.up(1)); return false;">X</a></td>
	<td><%=h @char.name %><%= hidden_field_tag("attendance[#{@char.id}][id]", @char.id, {:class => 'char_id'}) %></td>
	<td><%=h @char.character_class %></td>
	<td><%= text_field_tag("attendance[#{@char.id}][notes]", nil, { :style => "width: 100%;", :class => 'text' }) %></td>
	<td style="color: #ccc; text-align: right; font-weight: bold;"><%= @count %></td>
</tr>

app/views/admin/events/_event_form_fields.html.erb
<div class="fieldrow">
	<label for="event[title]">Title</label>
	<div class="field"><%= text_field(:event, :title, {:class => 'text', :style => 'width: 400px;'}) %></div>
</div>

<div class="fieldrow">
	<label for="event[start_date]">Date</label>
	<div class="field">
		<%= text_field(:event, :start_date, {:id => 'event_start_date', :class => 'text', :style => 'width: 100px;', :onfocus => "datePickerController.show(this.id);", :onblur => "datePickerController.hide(this.id);", :readonly => true}) %>
		<script type="text/javascript">
			var opts = {                      
				formElements:{"event_start_date":"Y-ds-m-ds-d"},
				statusFormat:"l-cc-sp-d-sp-F-sp-Y",
				rangeLow:"<%= Time.new.strftime("%Y%m%d") %>",
				noFadeEffect:true,
				noDrag:true,
				finalOpacity:97
			};      

			datePickerController.createDatePicker(opts);
		</script>
	</div>
</div>

<div class="fieldrow">
	<label for="event[start_time]">Start Time</label>
	<div class="field"><%= time_select(:event, :start_time, {:minute_step => 15, :ignore_date => true}) %> (<%= Time.zone.now.strftime("%Z") %>)</div>
</div>

<div class="fieldrow">
	<label for="event[organizer]">Organizer</label>
	<div class="field"><%= select_tag('event[organizer]', options_for_select(@_GUILD.main_characters.find(:all, :order => 'name ASC').collect{ |c| [c.name, c.id] }, @_MAIN_CHAR.id), {:style => "width: 140px;"}) %></div>
</div>

<div class="fieldrow">
	<label for="event[attendance_policy]">Attendance</label>
	<div class="field">
		<select name="event[attendance_policy]">
			<option <%= 'selected="selected"' if (@event.attendance_policy == 'required') %> value="required">Required</option>
			<option <%= 'selected="selected"' if (@event.attendance_policy == 'optional') %> value="optional">Optional</option>
			<option <%= 'selected="selected"' if (@event.attendance_policy == 'bonus') %> value="bonus">Bonus</option>
		</select>
	</div>
</div>

<div class="fieldrow">
	<label for="event[comments]">Comments</label>
	<div class="field"><%= text_area(:event, :comments, :style => "width: 400px; height: 4em;") %></div>
</div>

app/views/admin/events/edit.html.erb
<% title h("#{@_GUILD.name} Manage Calendar") %>
<div id="GuildManage_Calendar_Edit">
	<h1 class="GuildTitle"><%= @_GUILD.name %> Management: Calendar</h1>

	<% form_for([:admin, @event], :url => admin_event_url(@event), :method => :put, :html => { :class => 'srsform'}) do %>
		<fieldset>
			<legend>Editing Event</legend>
			
			<%= render :partial => 'event_form_fields' %>
		
			<div class="buttonrow">
				<% center_buttons do %>
					<button type="submit" class="button positive">
						<%= image_tag('icons/tick.png') %> save changes
					</button>
					<% link_to(admin_event_url(@event), :class => "button negative") do %>
						<%= image_tag('icons/cross.png') %> cancel
					<% end %>
				<% end %>
			</div>
		</fieldset>
	<% end %>
	
</div>

app/views/admin/events/index.html.erb
<% title h("#{@_GUILD.name} Manage Calendar") %>
<div id="GuildManage_Calendar">
	<h1 class="GuildTitle"><%= @_GUILD.name %> Management: Calendar</h1>

	<div class="SectionHeading">
		<h2>Current Raid Week</h2>
	</div>
	<%= schedule(:day => Date.today, :first_day_of_week => 2, :show_today => true, :show => @this_week, :admin => true).html_safe %>

	<p id="NewEventToggle">
		<button class="button" onclick="$('NewEventToggle').hide(); $('NewEvent').show();">
			<%= image_tag('icons/add.png') %> new event
		</button>
		<div class="clear"></div>
	</p>

	<div id="NewEvent" style="display: none;">
		<% form_tag(admin_events_url, :method => :post, :class => 'srsform') do %>
			<fieldset>
				<legend>Create New Event</legend>

				<%= render :partial => 'event_form_fields' %>

				<div class="buttonrow">
					<% center_buttons do %>
						<button type="submit" class="button positive">
							<%= image_tag('icons/tick.png') %> create
						</button>
						<%= link_to_function("#{image_tag('icons/cross.png')} cancel", "$('NewEvent').hide(); $('NewEventToggle').show()", :class => 'button negative') %>
					<% end %>
				</div>
			</fieldset>
		<% end %>
	</div>

	<% if @current_event and @current_event.calendar_event_attendances.blank? %>
		<div id="RecordAttendance">
			<div class="SectionHeading">
				<h2>Record Attendance</h2>
			</div>
			<p><strong><%=h @current_event.title %></strong> &mdash; <%= @current_event.begins_at.strftime("%m/%d/%y @ %H:%M (%Z)") %></p>
			<%= render :partial => 'attendance_edit', :locals => {:event => @current_event} %>
		</div>
	<% end %>

	<div class="SectionHeading">
		<h2>Future Events</h2>
	</div>
	<% if @future_events.blank? %>
		<p>There are no events scheduled after the end of the current raid week.</p>
	<% else %>
		<table class="eventlist">
			<tr>
				<th style="width: 160px; vertical-align: bottom;">When</th>
				<th style="vertical-align: bottom;">Event</th>
				<th style="width: 80px; text-align: center;">Signups</th>
			</tr>

			<% @future_events.each do |e| %>
				<tr>
					<td><%= e.begins_at.strftime("%m/%d/%y @ %H:%M (%Z)") %></td>
					<td><%= link_to(e.title, admin_event_url(e)) %></td>
					<td style="text-align: center;"><%=h e.calendar_event_signups.size %></td>
				</tr>
			<% end %>
		</table>
	<% end %>

	<div class="SectionHeading">
		<h2>Recent Events</h2>
	</div>
	<% if @recent_events.blank? %>
		<p>There are no recent events.</p>
	<% else %>
		<table class="eventlist">
			<tr>
				<th style="width: 160px; vertical-align: bottom;">When</th>
				<th style="vertical-align: bottom;">Event</th>
				<th style="width: 80px; text-align: center;">Attendance</th>
			</tr>

			<% @recent_events.each do |e| %>
				<tr>
					<td><%= e.begins_at.strftime("%m/%d/%y @ %H:%M (%Z)") %></td>
					<td><%= link_to(e.title, admin_event_url(e)) %></td>
					<td style="text-align: center;">
						<%=h e.calendar_event_attendances.size %>/<%=h e.calendar_event_signups.size %>
						<% if e.calendar_event_signups.size > 0 %>
							(<%= number_to_percentage(e.calendar_event_attendances.size/e.calendar_event_signups.size*100, :precision => 0) %>)
						<% end %>
					</td>
				</tr>
			<% end %>
		</table>
	<% end %>

</div>

app/views/admin/events/show.html.erb
<% title h("#{@_GUILD.name} Manage Calendar") %>
<div id="GuildManage_Calendar_Show">
	<h1 class="GuildTitle"><%= @_GUILD.name %> Management: Calendar</h1>

	<div id="InCalendarNav">
		<div class="grid_3 alpha">
			<% unless @prev_event.nil? %>
				<% link_to(admin_event_url(@prev_event), :class => 'button') do %>
					<%= image_tag('icons/arrow_left.png') %> prev event
				<% end %>
			<% end %>
		</div>
		
		<div class="grid_4">
			<% center_buttons do %>
				<% link_to(admin_events_url, :class => 'button') do %>
					<%= image_tag('icons/arrow_turn_left.png') %> back to calendar
				<% end %>
			<% end %>
		</div>
		
		<div class="grid_3 omega clearfix">
			<% unless @next_event.nil? %>
				<% link_to(admin_event_url(@next_event), :class => 'button clearfix', :style => 'float: right;') do %>
					next event <%= image_tag('icons/arrow_right.png') %>
				<% end %>
			<% end %>
		</div>
	</div>
	
	<div class="SectionHeading">
		<h2><%=h @event.title %></h2>
		<div class="heading_info"><%= @event.begins_at.strftime("%m/%d/%Y / %I:%M %p (%Z)") %></div>
	</div>
	
	<div id="EventSummary">
		<div style="float: right;">
			<% if @event.begins_at > Time.new %>
				<% link_to(edit_admin_event_url(@event), :class => 'button', :style => "margin-top: 0;") do %>
					<%= image_tag('icons/date_edit.png') %> edit event
				<% end %>

				<% link_to(admin_event_plan_url(@event), :class => 'button', :style => "margin-top: 0;") do %>
					<%= image_tag('icons/date_go.png') %> event plan
				<% end %>
			<% end %>
			<% link_to(admin_event_url(@event), :method => :delete, :confirm => "Are you sure you want to delete this event? This will also delete any signup and attendance data for this event.", :class => 'button negative', :style => "margin-top: 0;") do %>
				<%= image_tag('icons/date_delete.png') %> delete event
			<% end %>
			<div class="clear"></div>
		</div>

		<p class="organizer">Organizer: <%= link_to(@event.organizer.name, :controller => 'roster', :action => 'show', :id => @event.organizer) %></p>
		<p class="attendance">Attendance Policy: <%=h @event.attendance_policy.capitalize %></p>

		<% unless @event.comments.blank? %>
			<div class="comments">
				<h3>Comments</h3>
				<p><%=h @event.comments %></p>
			</div>
		<% end %>
	</div>

	<% if @event.begins_at < Time.new %>
		<div class="SectionHeading">
			<h3>Attendance</h3>
		</div>

		<div id="EventAttendance">
			<% if @event.calendar_event_attendances.blank? %>
				<p style="padding: 6px 0;">Note: <strong>No attendance has been recorded for this event yet</strong>, characters signed up for the event have been added to the attendance list below. Please make corrections and click save to record attendance.</p>
			<% end %>

			<%= render :partial => 'attendance_edit', :locals => {:event => @event} %>
		</div>
	<% end %>
	
	<div class="SectionHeading">
		<h3>Signups</h3>
	</div>

	<div id="EventSignup">
		<% if (Time.new > (@event.begins_at + 4.hours)) %>
			<p id="event_past_notice">This event has already occurred, see <%= show_signups_link("who was signed up") %> when the event started.</p>
		<% end %>

		<div id="calendar_all_signups" <% if (Time.new > (@event.begins_at + 4.hours)) %>style="display: none;"<% end %>>
			<% if @event.calendar_event_signups.blank? %>
				<p>Nobody is signed up for this event.</p>
			<% else %>
				<table class="simple">
					<tr>
						<th style="width: 30px;"></th>
						<th style="width: 150px;">Name</th>
						<th style="width: 100px;">Class</th>
						<th style="width: 125px;">Role Preference</th>
						<th>Comments <span style="font-weight: normal; font-size: 0.9em;">(Hover mouse to expand truncated comments.)</span></th>
					</tr>
		
					<% @event.calendar_event_signups.each_with_index do |signup, count| %>
						<tr>
							<td><%= count+1 %>.</td>
							<td><%=h signup.character.name %></td>
							<td><%= character_class_with_colorbox(signup.character.character_class) %></td>
							<td><%=h printable_role_preference(signup.role_preference) %></td>
							<td><%= p_truncated_at(signup.comments, 60) %></td>
						</tr>
					<% end %>
				</table>
			<% end %>
		</div>
	</div>
</div>