config/routes.rb
Srsguild::Application.routes.draw do
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'signup' => 'accounts#new', :as => :signup

  resources :sessions
  namespace :backend, :conditions => { :subdomain => 'admin' } do
    resource :dashboard

    match '' => 'backend/dashboards#show', :as => :backend_root, :via => :get
  end

  namespace :admin do
    resource :dashboard
    resources :events do
      collection do
        post :char_attendance_row
      end

      member do
        put :update_attendance
      end

      resource :plan do
        member do
          get :stats
        end
      end
    end

    resources :plans, :only => [:index]
    resources :balances do
      member do
        post :filter
      end
    end

    resources :roster, :only => [:index] do
      collection do
        put :update_all
      end

      member do
        put :gkick
        get :create_sms
        put :send_sms
      end
    end

    resources :settings, :only => [:index] do
      collection do
        put :update_all
      end
    end
  end

  resource :guild do
    collection do
      get :_armory_sync_status
      put :_acknowledge_armory_sync_complete
    end
  end

  resources :events, :only => [:index, :show] do
    collection do
      get :attendance
    end

    resource :signup, :only => [:create, :update, :destroy] do
      member do
        put :toggle
      end
    end

    resource :plan, :only => [:show]
  end

  resources :balances do
    member do
      post :filter
    end

    match 'balances/:balance_id/history/:char_id' => 'balances#history', :as => :balance_history, :via => :get
  end

  resources :roster, :only => [:index, :show] do
    collection do
      post :filter
    end
  end

  resource :account do
    member do
      get :success
      get :confirm
      put :resend_confirmation
      get :verify
      put :verify_manual
      get :forgot
      post :remind
      get :new_password
      put :reset_password
    end

    resources :characters, :only => [:index, :new, :create, :destroy, :update] do
      member do
        post :join
        get :find_guild
        post :find_guild
        get :withdraw
        get :armory_update
        get :promote
      end
    end
  end

  match '/account/new_password/:reset_code' => 'accounts#new_password'


  #match '/api/:controller/:action/:id' => '#index', :api => true
  #match '/api/wow/realms.:format' => '/api/wow#realms', :via => :get
  #match '/api/wow/realms/:region.:format' => '/api/wow#realms', :via => :get
  #match '/api/wow/realms/:region/:subregion.:format' => '/api/wow#realms', :via => :get
  #match '/api/wow/realms/:region/:subregion/:realm_type.:format' => '/api/wow#realms', :via => :get

  #match '' => 'guilds#show', :as => :guild_root, :via =>

  match '/' => 'home#index', as: :root
  match 'contact' => 'home#contact', :as => :contact
  match 'security' => 'home#security', :as => :security
  match 'tour' => 'home#tour', :as => :tour
  match 'pricing' => 'home#pricing', :as => :pricing

  match '/:controller(/:action(/:id))'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :check_login
  
  def index
    #redirect_to :controller => '/guild' and return if @_GUILD
    #redirect_to accounts_url and return if @_USER
    
    @header_bonus_template = 'home/index_header_bonus' unless @_USER
  end
  
  def tour
  end

  def pricing
  end
  
  def contact
    @from_email = flash[:from_email] if flash[:from_email]
    @message = flash[:message] if flash[:message]
  end
  
  def contact_submit
    redirect_to contact_url unless request.post?
    
    if params[:from_email].blank? or params[:message].blank?
      flash[:from_email] = params[:from_email]
      flash[:message] = params[:message]
      flash[:error] = "Please complete all fields and submit your message again."
    else
      if Srsmailer.deliver_contact_form(params[:from_email], params[:message])
        flash[:notice] = "Your message has been sent. Thanks!"
      else
        flash[:error] = "Whoops, there was a problem sending your message. Sorry! Try sending an email instead."
      end
    end
    
    redirect_to contact_url and return
  end
  
  def security
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_index_header_bonus.html.erb
<div id="Homepage_Bonus_FindGuild">
	<p>
		<strong>Looking for your guild?</strong>
		If you are new to <strong>srs</strong>guild,
		you should start by <%= link_to('signing up', new_account_url) %> 
		for a free account.
	</p>
</div>

app/views/home/contact.html.erb
<% title 'contact us' %>
<div id="Contact">
	<h1>Contact</h1>
	
	<div class="grid_8 alpha">
		<p>
			Got something on your mind? Well, you can always 
			<%= link_to('send us an email', 'mailto:support@srsguild.com') %> or 
			just fill out the form below. One of our specially trained support 
			pandas will ponder your query for a few minutes, maybe munch on some
			bamboo, and then send you a response as soon as possible!
		</p>
		
		<p>
			<em>If you have a concern about the safety or security of this 
			application, you might want to review the information and resources
			available on our <%= link_to('security page', security_url) %> 
			instead of using this form.</em>
		</p>
	</div>
	<div class="clear"></div>
	
	<% form_tag({:controller => 'home', :action => 'contact_submit'}, :method => :post, :class => 'srsform') do %>
		<div class="fieldrow">
			<label for="from_email">Your Email Address:</label>
			<div class="field"><%= text_field_tag(:from_email, @from_email, :size => 32, :class => 'text') %></div>
		</div>
		
		<div class="fieldrow">
			<label for="message">Your Message:</label>
			<div class="field">
				<%= text_area_tag(:message, @message, :cols => 64, :rows => 10, :class => 'text') %><br />
				<strong>(Don't send us your password or anything silly like that!)</strong>
			</div>
		</div>
		
		<div class="buttonrow">
			<% center_buttons do %>
				<button type="submit" class="button positive">
					<%= image_tag('icons/email.png') %> send message
				</button>
			<% end %>
		</div>
	<% end %>
</div>

app/views/home/index.html.erb
<div id="Homepage_Content">
	<div id="Homepage_UVP" class="grid_6 alpha">
		<h2>MVP</h2>
		<p>
			With <strong>srs</strong>guild, you'll spend less time on things like organization and records-keeping for
			your guild. Leaving you with more time to walk your dog, learn Japanese, or just troll the auction house!
		</p>
	</div>
	<div id="Homepage_Screen" class="grid_4 omega">
		<%= image_tag('home/screenshot.jpg', :size => '300x203') %>
	</div>
	
	<div class="clear"></div>
	
	<div id="Homepage_Trial_Signup" class="grid_10 highlight">
		<% form_tag do %>
			<select id="trial_region" name="region" style="">
				<option value="us">US</option>
				<option value="eu">EU</option>
			</select>
			
			<input type="text" class="text" id="trial_realm" name="realm" placeholder="realm" />
			<div id="trial_realm_choices" class="autocomplete" style="display: none;"></div>
			
			<input type="text" class="text" id="trial_guild" name="trial_guild" placeholder="guild" />
			
			<input type="submit" value="go" />
		<% end %>
		
		<script type="text/javascript" charset="utf-8">
			$('trial_region').observe('change', function() {
				$('trial_realm').value = '';
				$('trial_guild').value = '';
			});
			
			new Ajax.Autocompleter("trial_realm", "trial_realm_choices", "/api/wow/realms", {
				minChars: 3,
				frequency: 0.25,
				parameters: "as=ul",
				callback: function(input, qstr) {
					return qstr + '&region=' + $('trial_region').options[$('trial_region').selectedIndex].value;
				}
			});
		</script>
	</div>
	
	<div class="clear"></div>
	
	<div id="Homepage_Features" class="grid_9">
		<div class="grid_3 alpha">
		</div>

		<div class="grid_3">
		</div>

		<div class="grid_3 omega">
		</div>
	</div>
	
	<div class="clear"></div>
	
	<!--
	<div id="Homepage_Quote" class="grid_9">
		<blockquote>
			&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.&rdquo;

			<cite>
				&mdash;Some Celebrity
			</cite>
		</blockquote>
	</div>
	-->
</div>

app/views/home/pricing.html.erb
<% title 'pricing' %>
<div id="Home_Pricing">
	<h1>Pricing</h1>
	
	<p style="text-align: center; font-size: 18px;">
		During our beta, all <strong>srs</strong>guild services will be
		<em>totally free</em>.
	</p>
	
	<p>
		That being said, we do plan to start charging a monthly fee in the
		future for each guild that chooses to use our service. We have not
		yet finalized anything regarding pricing. 
		<%= link_to('Send us your feedback', contact_url) %> and tell us what 
		we are worth!
	</p>
	
	<p>
		<em>Rest assured</em>, we will provide all of our beta users with 
		ample warning before we start charging for our service. And, while
		we can't promise anything specific, it's a pretty safe bet that we'll 
		find a way to reward our beta testers when the time comes.
	</p>
		
	<p>
		We are working hard to create a product worthy of your business. 
		Specifically we want to save you as much time and hassle as we can, 
		so if you know of a way we can make your life easier, please 
		<%= link_to('let us know', contact_url) %>.
	</p>
</div>

app/views/home/security.html.erb
<% title 'security' %>
<div id="Security_Page">
	<h1>Security</h1>
	
	<p>
		We like to think we run a pretty tight ship around here, but we sure
		aren't perfect. If you believe you have found a flaw or vulnerability 
		in our application, please contact us immediately at 
		<%= link_to('security@srsguild.com', 'mailto:security@srsguild.com') %>.
		Please use our PGP compatible <%= link_to('public key', '/srsguild.pub') %>
		if you need to encrypt your message and provide us with a secure
		way to respond to your message if necessary. If you haven't heard back
		from us in 24 hours, please follow up with another email or ping us
		<%= link_to('on Twitter', 'http://twitter.com/srsguild') %>.
	</p>
	
	<p>
		If you have any non-security related questions or concerns, please
		direct those to our normal support pandas either by email 
		(<%= link_to('support@srsguild.com', 'mailto:support@srsguild.com') %>)
		or by using our <%= link_to('contact form', contact_url) %>.
	</p>
</div>

app/views/home/tour.html.erb
<% title 'tour' %>
<div id="Home_Tour">
	<h1>Tour</h1>
	<p style="font-size: 16px;">
		Learn a bit more about <strong>srs</strong>guild below. While we do 
		our best to keep this tour up to date, we are adding new features all
		the time, so the best way to explore our service is to 
		<%= link_to('sign up for free', signup_url) %> and experience it
		for yourself!
	</p>
	
	<div class="TourBlock">
		<div class="TourBlockScreenshot">
			<%= image_tag('tour/event_signup.png') %>
		</div>

		<h2>Schedule Events</h2>
		
		<p>
			With our simple interface, you can schedule a week's 
			worth of events in under a minute. And your guild members can 
			sign up for those events even faster.
		</p>
		
		<p>
			Users can easily indicate their preferred group role and leave
			other comments with their signup, letting raid leaders know
			what to expect when it's time to send out invites.
		</p>
		
		<p>
			The events calendar is fully timezone aware so all users will see
			the correct date and time for every event. No confusion.
		</p>
		
		<div class="clear"></div>
	</div>

	<div class="TourBlock">
		<div class="TourBlockScreenshot">
			<%= image_tag('tour/record_attendance.png') %>
		</div>
		
		<h2>Record Attendance</h2>
		
		<p>
			After an event, you can quickly record who attended. To speed 
			things along, everyone who was signed up for the event is 
			automatically copied into the attendance form. All you have to
			do is make corrections, add some individual comments if you want,
			and hit submit!
		</p>
		
		<p>
			Your members can then log in and review their attendance history
			at any time. And if you've made a mistake, you can correct it in 
			seconds.
		</p>
		
		<p>
			Events can be marked as "required", "optional", or "bonus" which
			lets you control how an event will impact attendance 
			calculations. You can reward users for showing up to an 
			unscheduled weekend	raid or track attendance to your casual 
			farming runs without impacting those who didn't attend.
		</p>
		
		<div class="clear"></div>
	</div>

	<div class="TourBlock">
		<div class="TourBlockScreenshot">
			<%= image_tag('tour/balance_adjust.png') %>
		</div>

		<h2>Track Balances</h2>
		
		<p>
			You can easily maintain a list of point balances for each
			member of your guild. In fact, you can maintain as many different
			sets of balances as you want. These sets are called 
			"Balance Accounts" and each can be configured independently to do
			things like maintain a zero-sum or calculate an automatic weekly
			point decay.
		</p>
		
		<p>
			Every transaction automatically records who	made the adjustment 
			and when. Each change can also include comments and be associated 
			with an event from your calendar. This means you (and your guild 
			members) have a full, reviewable history for every account.
		</p>
		
		<div class="clear"></div>
	</div>

	<div class="TourBlock">
		<div class="TourBlockScreenshot">
			<%= image_tag('tour/roster_view.png') %>
		</div>

		<h2>Review Your Roster</h2>
		
		<p>
			At a glance, you can see each member's attendance frequency and
			when they last attended an event. Drill down to see a member's
			character information, account balances, and full attendance
			history on one convenient page.
		</p>
		
		<p>
			Each guild account on our service can configure a unique "join 
			code" so that members can join themselves to the guild without
			needing an administrator's intervention. But don't worry, if 
			someone gets in that you don't want, it's easy to boot them out.
		</p>
		
		<div class="clear"></div>
	</div>

	<div class="TourBlock">
		<div class="TourBlockScreenshot">
			<%= image_tag('tour/account_settings.png') %>
		</div>

		<h2>Manage Your Account</h2>
		
		<p>
			When you set up your account, we pull in basic information
			about your character directly from the World of Warcraft Armory.
			You can then add things like your default group role, timezone,
			etc.
		</p>
		
		<p>
			You can even add your Alts to your account, although at the 
			moment you can't sign up for events with them. (We're working
			on it!)
		</p>
		
		<div class="clear"></div>
	</div>

	<p style="font-size: 16px; text-align: center;">
		Heard enough? Want to see it for yourself? <%= link_to('Sign up now!', signup_url) %>
	</p>
	
</div>