config/routes.rb
Srsguild::Application.routes.draw do
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'signup' => 'accounts#new', :as => :signup

  resources :sessions
  namespace :backend, :conditions => { :subdomain => 'admin' } do
    resource :dashboard

    match '' => 'backend/dashboards#show', :as => :backend_root, :via => :get
  end

  namespace :admin do
    resource :dashboard
    resources :events do
      collection do
        post :char_attendance_row
      end

      member do
        put :update_attendance
      end

      resource :plan do
        member do
          get :stats
        end
      end
    end

    resources :plans, :only => [:index]
    resources :balances do
      member do
        post :filter
      end
    end

    resources :roster, :only => [:index] do
      collection do
        put :update_all
      end

      member do
        put :gkick
        get :create_sms
        put :send_sms
      end
    end

    resources :settings, :only => [:index] do
      collection do
        put :update_all
      end
    end
  end

  resource :guild do
    collection do
      get :_armory_sync_status
      put :_acknowledge_armory_sync_complete
    end
  end

  resources :events, :only => [:index, :show] do
    collection do
      get :attendance
    end

    resource :signup, :only => [:create, :update, :destroy] do
      member do
        put :toggle
      end
    end

    resource :plan, :only => [:show]
  end

  resources :balances do
    member do
      post :filter
    end

    match 'balances/:balance_id/history/:char_id' => 'balances#history', :as => :balance_history, :via => :get
  end

  resources :roster, :only => [:index, :show] do
    collection do
      post :filter
    end
  end

  resource :account do
    member do
      get :success
      get :confirm
      put :resend_confirmation
      get :verify
      put :verify_manual
      get :forgot
      post :remind
      get :new_password
      put :reset_password
    end

    resources :characters, :only => [:index, :new, :create, :destroy, :update] do
      member do
        post :join
        get :find_guild
        post :find_guild
        get :withdraw
        get :armory_update
        get :promote
      end
    end
  end

  match '/account/new_password/:reset_code' => 'accounts#new_password'


  #match '/api/:controller/:action/:id' => '#index', :api => true
  #match '/api/wow/realms.:format' => '/api/wow#realms', :via => :get
  #match '/api/wow/realms/:region.:format' => '/api/wow#realms', :via => :get
  #match '/api/wow/realms/:region/:subregion.:format' => '/api/wow#realms', :via => :get
  #match '/api/wow/realms/:region/:subregion/:realm_type.:format' => '/api/wow#realms', :via => :get

  #match '' => 'guilds#show', :as => :guild_root, :via =>

  match '/' => 'home#index', as: :root
  match 'contact' => 'home#contact', :as => :contact
  match 'security' => 'home#security', :as => :security
  match 'tour' => 'home#tour', :as => :tour
  match 'pricing' => 'home#pricing', :as => :pricing

  match '/:controller(/:action(/:id))'
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController

  def index
    @this_week = @_GUILD.calendar_events.find(:all, :conditions => CalendarEvent.conditions_for_raid_week(Date.today), :order => "begins_at ASC")
    @future_events = @_GUILD.calendar_events.find(:all, :conditions => ["begins_at > ?", CalendarEvent.end_of_raid_week(Date.today) - Time.new.gmt_offset], :order => "begins_at ASC")
    @recent_events = @_GUILD.calendar_events.find(:all, :conditions => "begins_at < UTC_TIMESTAMP()", :order => "begins_at DESC", :limit => 5)
    
    @current_event = @_GUILD.calendar_events.find(:first, :conditions => ["begins_at < ?", Time.new], :order => "begins_at DESC")
    @new_attendance = CalendarEventAttendance.new
    
    @event = CalendarEvent.new
    @event.start_time = @_GUILD.guild_config.c_default_start_time if @_GUILD.guild_config.c_default_start_time
  end
  
  def show
    @event = @_GUILD.calendar_events.find(params[:id])

    @prev_event = @_GUILD.calendar_events.find(:first, :conditions => ["begins_at < ?", @event.begins_at], :order => "begins_at DESC")
    @next_event = @_GUILD.calendar_events.find(:first, :conditions => ["begins_at > ?", @event.begins_at], :order => "begins_at ASC")
  end
  
  def create
    @new_event = CalendarEvent.new(params[:event])
    @new_event.start_time = "#{params[:event]['start_time(4i)']}:#{params[:event]['start_time(5i)']}" # Ergh.
    @new_event.organizer = @_GUILD.characters.find(params[:event][:organizer])
    @new_event.guild = @_GUILD

    if @new_event.save
      flash[:notice] = "New event created successfully."
    else
      flash[:error] = "Unable to create new event."
    end

    redirect_to :action => 'index' and return
  end
  
  def edit
    @event = @_GUILD.calendar_events.find(params[:id])
  end
  
  def update
    event = @_GUILD.calendar_events.find(params[:id])
    
    event.attributes = params[:event]
    event.start_time = "#{params[:event]['start_time(4i)']}:#{params[:event]['start_time(5i)']}" # Ergh.
    event.organizer = @_GUILD.characters.find(params[:event][:organizer])

    if event.save
      flash[:notice] = "Event details updated successfully."
    else
      flash[:error] = "Unable to update event details."
    end
    
    redirect_to :action => 'show', :id => event and return
  end
  
  def update_attendance
    event = @_GUILD.calendar_events.find(params[:id])
    
    event.calendar_event_attendances.clear
    
    unless params[:attendance].blank?
      params[:attendance].each do |char_id, att|
        char = @_GUILD.characters.find(att['id'].to_i)
      
        new_att = CalendarEventAttendance.new
        new_att.character = char
        new_att.calendar_event = event
        new_att.comments = att['notes']
      
        new_att.save!
      end
    end
    
    flash[:notice] = "Event attendance updated."
    redirect_to :action => 'show', :id => event.id and return
  end
  
  def destroy
    event = @_GUILD.calendar_events.find(params[:id])
    
    if event.begins_at > Time.new
      event.destroy
    else
      event.is_deleted = true
      event.save!
    end
    
    flash[:notice] = "Event deleted."
    redirect_to admin_events_url and return
  end
  
  # AJAX methods
  # --------------------------------------------------------------------------
  
  def char_attendance_row
    @char = @_GUILD.main_characters.find_by_name(params[:character_name])
    #@char = Character.find_by_name(params[:character_name])
    @count = params[:count].to_i || ""

    if @char.nil?
      render :text => "Not found.", :status => :forbidden, :layout => false and return
    end
    
    exclude = JSON.parse(params[:exclude])
    
    if exclude.any? { |id| id.to_i == @char.id }
      render :text => "That person is already on the list!", :status => :forbidden, :layout => false and return
    end
    
    render :partial => 'char_attendance_row', :layout => false
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  before_filter :require_login
  before_filter :require_guild
  
  def index
    @this_week = @_GUILD.calendar_events.find(:all, :conditions => CalendarEvent.conditions_for_raid_week(Date.today), :order => "begins_at ASC")
    @next_week = @_GUILD.calendar_events.find(:all, :conditions => CalendarEvent.conditions_for_raid_week(Date.today + 7), :order => "begins_at ASC")
    @past_events = @_GUILD.calendar_events.find(:all, :conditions => ["begins_at < ?", Time.new], :order => "begins_at DESC", :limit => 10, :include => :calendar_event_attendances)
  end
  
  def show
    @event = @_GUILD.calendar_events.find(params[:id])
    redirect_to :action => 'index' and return if @event.nil?
    
    @prev_event = @_GUILD.calendar_events.find(:first, :conditions => ["begins_at < ?", @event.begins_at], :order => "begins_at DESC")
    @next_event = @_GUILD.calendar_events.find(:first, :conditions => ["begins_at > ?", @event.begins_at], :order => "begins_at ASC")
    
    @plan_group_slots = Array.new

    (0..7).each do |i|
      @plan_group_slots[i] = Array.new
    end
    
    @event.event_plan_slots.find(:all, :order => 'group_position ASC').each do |s|
      @plan_group_slots[((s.group_position.to_f-1.0)/5.0).floor.to_i].push(s)
    end
    
    @personal_signup = @_MAIN_CHAR.calendar_event_signups.find(:first, :conditions => ["calendar_event_id = ?", @event.id])
  end

  def attendance
    @events = CalendarEvent.paginate :page => params[:page], :order => 'begins_at DESC', :per_page => 20, :conditions => ["guild_id = ? AND begins_at < ?", @_GUILD.id, Time.new], :include => :calendar_event_attendances
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper

  def admin_calendar_event_link(event)
    return link_to(event.begins_at.strftime("%H:%M"), admin_event_url(event), :title => event.title)
  end
end

app/helpers/events_helper.rb
module EventsHelper

  def calendar_event_link(event)
    "<a href=\"#\" id=\"event_link_#{event.id}\" onclick=\"return false;\">#{event.begins_at.strftime("%H:%M")}</a>\n"
  end
  
  def calendar_signup_role_options
    [
      ['', ''],
      ['Tank', 'tank'],
      ['Healer', 'healer'],
      ['Melee DPS', 'melee_dps'],
      ['Ranged DPS', 'range_dps']
    ]
  end
  
  def printable_role_preference(pref)
    return case pref
      when 'tank' then "Tank"
      when 'healer' then "Healer"
      when 'melee_dps' then "Melee DPS"
      when 'range_dps' then "Ranged DPS"
      else "--"
    end
  end
  
  def p_truncated_at(str, len)
    if str.blank?
			return "<p>--</p>"
		else
			if str.length > len
				"<p title=\"#{html_escape(str)}\">#{html_escape(str[0,len])}...</p>"
			else
				"<p>#{html_escape(str)}</p>"
			end
		end
  end
  
  def show_signups_link(str)
		return link_to_function(str, nil) do |page|
	    page[:calendar_all_signups].show
	    page[:event_past_notice].hide
	  end
  end
end

app/views/events/_single_week.html.erb
<%=raw schedule(:day => date, :first_day_of_week => 2, :show_today => true, :show => events) %>
<script type="text/javascript" charset="utf-8">
	<% events.each do |e| %>
		new Tip($('event_link_<%= e.id %>'),
		{
			ajax: { url: '<%= event_url(e) %>', options: { method: 'get' } },
			title: '<%= link_to(escape_javascript(e.title), event_url(e)) %>',
			style: 'protogrey',
			stem: 'leftMiddle',
			showOn: 'click',
			hideOn: false,
			closeButton: true,
			hideOthers: true,
			hook: { target: 'rightMiddle', tip: 'leftMiddle', mouse: false },
			offset: { x: -7, y: 0 },
			width: 200
		});
	<% end %>
</script>

app/views/events/attendance.html.erb
<% title h("#{@_GUILD.name} Calendar") %>
<h1 class="GuildTitle"><%= @_GUILD.name %>: Calendar</h1>

<div class="clearfix">
	<% link_to(events_url, :class => 'button', :style => 'margin-top: 0;') do %>
		<%= image_tag('icons/arrow_turn_left.png') %> back to calendar
	<% end %>
</div>

<div class="SectionHeading">
	<h2>Your Attendance History</h2>
</div>
<%= render :partial => 'shared/attendance_list', :locals => { :events => @events, :char => @_MAIN_CHAR } %>

<%= will_paginate @events %>

app/views/events/index.html.erb
<% title h("#{@_GUILD.name} Calendar") %>
<div id="CalendarIndex">

	<h1 class="GuildTitle"><%= @_GUILD.name %>: Calendar</h1>

	<div class="SectionHeading">
		<h2>Current Raid Week</h2>
	</div>
	<%= render :partial => 'single_week', :locals => { :date => Date.today, :events => @this_week } %>
	
	<div class="SectionHeading">
		<h2>Next Raid Week</h2>
	</div>
	<%= render :partial => 'single_week', :locals => { :date => (Date.today + 7.days), :events => @next_week } %>

	<div class="SectionHeading">
		<h2>Recent Attendance History</h2>
		<div class="heading_nav">
			<% link_to(attendance_events_url, :class => 'button') do %>
				<%= image_tag('icons/calendar.png') %> view all
			<% end %>
		</div>
	</div>
	<%= render :partial => 'shared/attendance_list', :locals => { :events => @past_events, :char => @_MAIN_CHAR } %>
</div>	

app/views/events/show.html.erb
<% title h("#{@_GUILD.name} Calendar") %>
<div id="CalendarShow">

	<h1 class="GuildTitle"><%= @_GUILD.name %>: Calendar</h1>

	<div id="InCalendarNav">
		<div class="grid_3 alpha">
			<% unless @prev_event.nil? %>
				<% link_to(event_url(@prev_event), :class => 'button') do %>
					<%= image_tag('icons/arrow_left.png') %> prev event
				<% end %>
			<% end %>
		</div>
		
		<div class="grid_4">
			<% center_buttons do %>
				<% link_to(events_url, :class => 'button') do %>
					<%= image_tag('icons/arrow_turn_left.png') %> back to calendar
				<% end %>
			<% end %>
		</div>
		
		<div class="grid_3 omega clearfix">
			<% unless @next_event.nil? %>
				<% link_to(event_url(@next_event), :class => 'button clearfix', :style => 'float: right;') do %>
					next event <%= image_tag('icons/arrow_right.png') %>
				<% end %>
			<% end %>
		</div>
	</div>
	
	<div class="SectionHeading">
		<h2><%=h @event.title %></h2>
		<div class="heading_info"><%= @event.begins_at.strftime("%m/%d/%Y / %I:%M %p (%Z)") %></div>
	</div>
	
	<div id="EventSummary">
		<p class="organizer"><em>Organizer:</em> <%= link_to(@event.organizer.name, roster_url(@event.organizer)) %></p>
		<p class="attendance"><em>Attendance Policy:</em> <%=h @event.attendance_policy.capitalize %></p>
		
		<% unless @event.comments.blank? %>
			<div class="comments">
				<h4>Organizer's Comments</h4>
				<p><%=h @event.comments %></p>
			</div>
		<% end %>
	</div>
	
	<% if @event.has_plan? %>
		<div id="EventPlan">
			<div class="SectionHeading">
				<h3>Group Plan</h3>
			</div>
			
			<div id="plan_event_groups" style="overflow: auto; width: 580px; margin: 0 auto;">
				<% @plan_group_slots.each_with_index do |group_chars, group_num| %>
					<div id="raid_group-<%= group_num+1 %>" class="raid_group" <% if (((group_num.to_i+1) % 4) == 1) %>style="clear: both;"<% end %>>
						<div class="group_label">Group <%= group_num+1 %></div>

						<div class="group_slots">
							<% group_chars.each do |gc| %>
								<div id="plan_char-<%= gc.character.id %>" class="plan_char in_group">
									<%= character_class_colorbox(gc.character.character_class) %> <%=h gc.character.name %> <%= "(<span title=\"#{h(gc.character.raid_spec)}\" style=\"cursor: help; border-bottom: 1px dotted silver;\">#{h(gc.character.raid_spec[0,1])}</span>)" unless gc.character.raid_spec.blank? %>
								</div>
							<% end %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	<% end %>

	<% if @event.begins_at < Time.new %>
		<div id="EventAttendance">
			<div class="SectionHeading">
				<h3>Attendance</h3>
			</div>

			<% if @event.calendar_event_attendances.blank? %>
				<p>No attendance for this event has been recorded.</p>
			<% else %>
				<% @event.calendar_event_attendances.each do |att| %>
					<div class="calendar_event_attendance <% if att.character == @_MAIN_CHAR %>highlight<% end %>">
						<p><%= att.character.name %></p>
					</div>
				<% end %>
			<% end %>
		</div>
	<% else %>
		<div id="EventPersonalSignup">
			<% if @personal_signup %>
				<div class="SectionHeading">
					<h3>Edit Your Signup</h3>
				</div>
				
				<% form_tag(event_signup_url(:event_id => @event), :method => :put) do %>
					<div class="highlight" style="padding: 8px;">
						<div style="overflow: auto; width: 740px;">
							<div style="width: 150px; float: left;">
								<label for="my_signup_character">Character</label><br />
								<%= select_tag('my_signup_character', options_for_select(@_USER.characters.collect{ |c| [c.name, c.id] }, @_MAIN_CHAR.id), :style => "width: 140px;", :disabled => true) %>
							</div>
				
							<div style="width: 150px; float: left;">
								<label for="my_signup_role">Preferred Role</label><br />
								<%= select_tag('my_signup_role', options_for_select(calendar_signup_role_options, @personal_signup.role_preference), :style => "width: 140px;") %>
							</div>

							<div style="width: 434px; float: left;">
								<label for="my_signup_comments">Comments</label><br />
								<%= text_field_tag('my_signup_comments', @personal_signup.comments, :style => "width: 434px;") %>
							</div>
						</div>

						<% center_buttons do %>
							<button type="submit" class="button positive" style="margin-left: 0; margin-bottom: 0;">
								<%= image_tag('icons/tick.png') %>save changes
							</button>
							<% link_to(event_signup_url(:event_id => @event), :method => :delete, :class => 'button negative', :style => 'margin-bottom: 0;') do %>
								<%= image_tag('icons/cross.png') %> cancel signup
							<% end %>
						<% end %>
					</div>
				<% end %>
			<% else %>
				<div class="SectionHeading">
					<h3>Signup for this Event</h3>
				</div>
				
				<% form_tag(event_signup_url(:event_id => @event), :method => :post) do %>
					<div class="highlight" style="overflow: auto; padding: 8px;">
						<div style="overflow: auto;">
							<div style="width: 150px; float: left;">
								<label for="my_signup_character">Character</label><br />
								<%= select_tag('my_signup_character', options_for_select(@_USER.characters.collect{ |c| [c.name, c.id] }, @_MAIN_CHAR.id), :style => "width: 140px;", :disabled => true) %>
							</div>
			
							<div style="width: 150px; float: left;">
								<label for="my_signup_role">Preferred Role</label><br />
								<%= select_tag('my_signup_role', options_for_select(calendar_signup_role_options, @_MAIN_CHAR.event_role_preference), :style => "width: 140px;") %>
							</div>

							<div style="width: 436px; float: left;">
								<label for="my_signup_comments">Comments</label><br />
								<%= text_field_tag('my_signup_comments', nil, :style => "width: 434px;") %>
							</div>
						</div>

						<% center_buttons do %>
							<button type="submit" class="button positive" style="margin-left: 0; margin-bottom: 0;">
								<%= image_tag('icons/tick.png') %> sign up
							</button>
						<% end %>
					</div>
				<% end %>
			<% end %>
		</div>
	<% end %>
	
	<div id="EventSignup">
		<div class="SectionHeading">
			<h3>All Signups</h3>
		</div>

		<% if (Time.new > (@event.begins_at + 4.hours)) %>
			<p id="event_past_notice">This event has already occurred, see <%= show_signups_link("who was signed up") %> when the event started.</p>
		<% end %>

		<div id="calendar_all_signups" <% if (Time.new > (@event.begins_at + 4.hours)) %>style="display: none;"<% end %>>
			<% if @event.calendar_event_signups.blank? %>
				<p>Nobody <%= (Time.new > (@event.begins_at + 4.hours)) ? 'was' : 'has' %> signed up for this event.</p>
			<% else %>
				<table class="simple">
					<tr>
						<th style="width: 30px;"></th>
						<th style="width: 175px;">Name</th>
						<th style="width: 150px;">Role Preference</th>
						<th>Comments <span style="font-weight: normal; font-size: 0.9em;">(Hover mouse to expand truncated comments.)</span></th>
					</tr>
		
					<% @event.calendar_event_signups.each_with_index do |signup, count| %>
						<tr class="<% if signup.character == @_MAIN_CHAR %>highlight<% end %>">
							<td><%= count+1 %>.</td>
							<td><%= link_to(signup.character.name, :controller => 'roster', :action => 'show', :id => signup.character) %></td>
							<td><%=h printable_role_preference(signup.role_preference) %></td>
							<td><%= p_truncated_at(signup.comments, 60) %></td>
						</tr>
					<% end %>
				</table>
			<% end %>
		</div>
	</div>
</div>

app/views/events/show.js.erb
<div class="event_detail">
	<p class="datetime"><%= @event.begins_at.strftime("%a %b %d @ %I:%M %p (%Z)") %></p>
	<p class="organizer">Organizer: <%=h @event.organizer.name %></p>
	
	<% if @event.begins_at > Time.new %>
		<%# Event has not yet occurred, show signup info. %>
		<div class="signup">
			<% if @_MAIN_CHAR.signed_up_for?(@event) %>
				<p id="event_<%= @event.id %>_signup_status" class="signup_status">You <span style="color: #0f0;">are</span> signed up to attend<br /> this event. (<%= link_to('edit', event_url(@event)) %>)</p>
			<% else %>
				<p id="event_<%= @event.id %>_signup_status" class="signup_status">You <span style="color: #f00;">are not</span> signed up to<br /> attend this event.</p>
			<% end %>
			
			<p class="signup_toggle"><%= button_to_remote('toggle signup status', { :update => "event_#{@event.id}_signup_status", :url => toggle_event_signup_url(:event_id => @event), :method => :put }) %></p>
		</div>
	<% else %>
		<%# Event has already occurred, show attendance info. %>

		<div class="attendance">
			<% if @_MAIN_CHAR.attended?(@event) %>
				<p class="signup_status">You were <span style="color: #0f0;">present</span> for this event.</p>
			<% else %>
				<p class="signup_status">You were <span style="color: #f00;">not present</span> for this event.</p>
			<% end %>
		</div>
	<% end %>
</div>