config/routes.rb
Srsguild::Application.routes.draw do
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'signup' => 'accounts#new', :as => :signup

  resources :sessions
  namespace :backend, :conditions => { :subdomain => 'admin' } do
    resource :dashboard

    match '' => 'backend/dashboards#show', :as => :backend_root, :via => :get
  end

  namespace :admin do
    resource :dashboard
    resources :events do
      collection do
        post :char_attendance_row
      end

      member do
        put :update_attendance
      end

      resource :plan do
        member do
          get :stats
        end
      end
    end

    resources :plans, :only => [:index]
    resources :balances do
      member do
        post :filter
      end
    end

    resources :roster, :only => [:index] do
      collection do
        put :update_all
      end

      member do
        put :gkick
        get :create_sms
        put :send_sms
      end
    end

    resources :settings, :only => [:index] do
      collection do
        put :update_all
      end
    end
  end

  resource :guild do
    collection do
      get :_armory_sync_status
      put :_acknowledge_armory_sync_complete
    end
  end

  resources :events, :only => [:index, :show] do
    collection do
      get :attendance
    end

    resource :signup, :only => [:create, :update, :destroy] do
      member do
        put :toggle
      end
    end

    resource :plan, :only => [:show]
  end

  resources :balances do
    member do
      post :filter
    end

    match 'balances/:balance_id/history/:char_id' => 'balances#history', :as => :balance_history, :via => :get
  end

  resources :roster, :only => [:index, :show] do
    collection do
      post :filter
    end
  end

  resource :account do
    member do
      get :success
      get :confirm
      put :resend_confirmation
      get :verify
      put :verify_manual
      get :forgot
      post :remind
      get :new_password
      put :reset_password
    end

    resources :characters, :only => [:index, :new, :create, :destroy, :update] do
      member do
        post :join
        get :find_guild
        post :find_guild
        get :withdraw
        get :armory_update
        get :promote
      end
    end
  end

  match '/account/new_password/:reset_code' => 'accounts#new_password'


  #match '/api/:controller/:action/:id' => '#index', :api => true
  #match '/api/wow/realms.:format' => '/api/wow#realms', :via => :get
  #match '/api/wow/realms/:region.:format' => '/api/wow#realms', :via => :get
  #match '/api/wow/realms/:region/:subregion.:format' => '/api/wow#realms', :via => :get
  #match '/api/wow/realms/:region/:subregion/:realm_type.:format' => '/api/wow#realms', :via => :get

  #match '' => 'guilds#show', :as => :guild_root, :via =>

  match '/' => 'home#index', as: :root
  match 'contact' => 'home#contact', :as => :contact
  match 'security' => 'home#security', :as => :security
  match 'tour' => 'home#tour', :as => :tour
  match 'pricing' => 'home#pricing', :as => :pricing

  match '/:controller(/:action(/:id))'
end

app/models/account.rb
require 'digest/sha1'

class Account < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :time_zone, :mobile_number
  
  has_one :guild, :foreign_key => 'owner_id'

  has_one :main_character, :class_name => "Character", :conditions => "is_main = 1"
  has_many :alt_characters, :class_name => "Character", :conditions => "is_main = 0"
  has_many :characters
  
  has_many :calendar_events
  
  attr_accessor :password, :password_confirmation, :skip_email_validation, :request_host
  
  validates_presence_of :email
  validates_presence_of :pw_hash
  validates_presence_of :pw_salt
  
  validates_uniqueness_of :email
  validates_uniqueness_of :email_verification_value, :allow_nil => true
  
  validates_confirmation_of :password
  
  validates_format_of :mobile_number, :with => /[0-9]*/, :allow_nil => true
  validates_length_of :mobile_number, :within => 10..15, :allow_nil => true

  before_validation :hash_password!
  before_validation :clean_mobile_number!
  
  after_create :verify_email
  
  def self.login(email, password)
    user = self.find(:first, :conditions => ["email = ? AND pw_hash = SHA1(CONCAT(?, pw_salt))", email, password])
    
    if user.nil?
      raise ZguildError::LoginFailed.new
    else
      user
    end
  end
  
  def is_verified?
    return (self[:email_verification_value].nil? and self[:email_verify_before].nil?)
  end
  
  def sms_enabled?
    return !self.mobile_number.blank?
  end

  def verify_email
    return if self.skip_email_validation == true
    
    self[:email_verification_value] = rand_str(6).upcase
    self[:email_verify_before] = Time.new + 7.days
    
    if self.valid?
      self.save
    elsif ((self.errors.size == 1) and (self.errors[:email_verification_value] != nil))
      while (self.invalid?) do
        self[:email_verification_value] = rand_str(6).upcase
      end
      
      self.save
    end
    
    Srsmailer.deliver_account_create_verify(self, self.request_host)
    
    return true
  end
  
  protected
  # -------------------------------------------
  
  def hash_password!
    unless password.nil?
      generate_salt! if pw_salt.nil?
      
      self.pw_hash = Digest::SHA1.hexdigest("#{password}#{pw_salt}")
    end
  end
  
  def generate_salt!
    self.pw_salt = Digest::SHA1.hexdigest(Time.now.to_s + rand(100000000).to_s)[1..20]
  end
  
  def clean_mobile_number!
    unless self.mobile_number.nil?
      self.mobile_number = self.mobile_number.gsub(/[^0-9]/, '')
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  before_filter :require_login, :except => [:new, :create, :confirm, :resend_confirmation, :verify, :forgot, :remind, :new_password, :reset_password]
  
  def show
    @account = @_USER
    @main_char = @account.main_character
    @alts = @account.alt_characters.find(:all, :order => 'name')
  end
  
  def new
    if flash[:new_account].blank?
      @account = Account.new
    else
      @account = Account.new(flash[:new_account])
    end
    
    unless current_subdomain.blank?
      @guild = Guild.find_by_subdomain(current_subdomain)
      redirect_to new_account_url(:subdomain => false) and return if @guild.nil?
      
      if flash[:new_character].blank?
        @character = Character.new
        @character.region = @guild.region
        @character.realm = @guild.realm
      else
        @character = Character.new(flash[:new_character])
      end

      @extended_fields = true if flash[:armory_error]
    end
  end
  
  def create
    Account.transaction do
      acct = Account.new(params[:account])
  		acct.request_host = request.host
  		acct.skip_email_validation = true unless current_subdomain.blank?

      if acct.save
        session[:logged_in] = true
        session[:user_id] = acct.id
      
        if (RAILS_ENV == 'development' and ['127.0.0.1', '::1'].include?(request.remote_ip))
          # Automatically confirm the account since it was created locally.
          acct.email_verification_value = nil
          acct.email_verify_before = nil
          acct.save!
        end
        
        unless current_subdomain.blank?
          guild = Guild.find_by_subdomain(current_subdomain)
          raise ActiveRecord::Rollback if guild.nil?

          if params[:guild_join_code].strip == guild.join_code
            char = Character.new(params[:character])
            char.account = acct
            char.guild = guild
            char.is_main = true
            char.guild_role = 'Initiate'

            if char.valid?
              char.save!

              acct.skip_email_validation = false
              acct.verify_email

              redirect_to success_account_url and return
            elsif char.errors.on_base.include?("armory_update_error")
              flash[:new_account] = params[:account]
              flash[:new_character] = params[:character]
              flash[:armory_error] = true

              raise ActiveRecord::Rollback
            else
              flash[:error] = "Whoops! Something was wrong with the character information you provided."
              flash[:errors] = char.errors
              flash[:new_account] = params[:account]
              flash[:new_character] = params[:character]

              raise ActiveRecord::Rollback
            end
          else
            flash[:error] = "The guild join code you provided was incorrect. Please check with your guild leaders for the correct code."
            flash[:new_account] = params[:account]
            flash[:new_character] = params[:character]

            raise ActiveRecord::Rollback
          end
        end

        redirect_to success_account_url and return
      else
        flash[:error] = "Whoops! Something was wrong with the new account information you provided."
        flash[:errors] = acct.errors
        
        raise ActiveRecord::Rollback
      end
    end
    
    redirect_to new_account_url
  end
  
  def update
    acct = @_USER
    
    params[:account][:password] = nil if params[:account][:password].blank?
    params[:account][:password_confirmation] = nil if params[:account][:password].blank?
    
    params[:account][:time_zone] = nil if params[:account][:time_zone].blank?
    
    acct.attributes = params[:account]
    
    if acct.save
      flash[:notice] = "Your account was successfully updated."
      redirect_to account_url and return
    else
      flash[:error] = "The new information you supplied for your account was not valid.<br /> If you are updating your password, please make sure both fields match."
      redirect_to account_url and return
    end
  end
  
  def success
  end
  
  def confirm
  end
  
  def resend_confirmation
    acct = Account.find(:first, :conditions => ["email = ? AND email_verification_value IS NOT NULL", params[:verify_email]])
    
    if acct != nil
      Srsmailer.deliver_account_create_verify(acct)
      flash[:notice] = "A new verification message has been sent."
    else
      flash[:error] = "No unverified account was found with that email address."
    end

    redirect_to confirm_account_url and return
  end
  
  def verify
    acct = Account.find(:first, :conditions => ["email_verification_value = ?", params[:verification_value].strip])
    
    if acct != nil
      acct.email_verification_value = nil
      acct.email_verify_before = nil
      acct.save!
      
      flash[:notice] = "Your email address has been verified! Please log in to continue."
      redirect_to login_url and return
    else
      flash[:error] = "Unable to find an account to verify using that code.<br />Perhaps you already verified your account?"
      redirect_to confirm_account_url and return
    end
  end
  
  def verify_manual
    verify
  end
  
  def forgot
    @email = flash[:email] if flash[:email]
  end
  
  def remind
    acct = Account.find(:first, :conditions => { :email => params[:email] })
    
    if acct.nil?
      flash[:error] = "Sorry, we were unable to find an account with that email address."
      flash[:email] = params[:email]
    else
      acct.password_reset_value = rand_str(16).upcase
      acct.password_reset_request_at = Time.new
      acct.password_reset_ip = request.ip
      
      acct.save!
      
      Srsmailer.deliver_account_password_reset_request(acct, request.host)
      
      flash[:notice] = "Reset email sent, please allow a few minutes for delivery."
    end
    
    redirect_to forgot_account_url and return
  end
  
  def new_password
    if params[:reset_code].blank?
      flash[:error] = "The reset code provided was invalid. Please try again or contact support."
      redirect_to forgot_account_url and return
    end
    
    @account = Account.find_by_password_reset_value(params[:reset_code])
    
    if (@account.nil? or (@account.password_reset_request_at < (Time.new - 1.days)))
      flash[:error] = "The reset code provided was invalid. Please try again or contact support."
      redirect_to forgot_account_url and return
    end
  end
  
  def reset_password
    if params[:reset_code].blank?
      flash[:error] = "The reset code provided was invalid. Please try again or contact support."
      redirect_to forgot_account_url and return
    end
    
    acct = Account.find_by_password_reset_value(params[:reset_code])
    
    if (acct.nil? or (acct.password_reset_request_at < (Time.new - 1.days)))
      flash[:error] = "The reset code provided was invalid. Please try again or contact support."
      redirect_to forgot_account_url and return
    end
    
    acct.password = params[:new_password]
    acct.password_confirmation = params[:new_password_confirmation]
    
    if acct.save
      acct.password_reset_value = nil
      acct.password_reset_request_at = nil
      acct.password_reset_ip = nil
      acct.save!
      
      flash[:notice] = "Your password was successfully updated. Go ahead and log in now!"
      redirect_to login_url and return
    else
      flash[:error] = "The password and password confirmation field did not match, please try again. Type carefully this time."
      redirect_to :action => 'new_password', :reset_code => params[:reset_code] and return
    end
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/views/accounts/_mobile_number_tooltip.html.erb
<strong>Why do you want my mobile number?</strong><br/>
<p style="margin: 5px 0 0 0;">
	Your guild may choose to utilize <strong>srs</strong>guild's SMS communication
	features. In order to participate, you will need to provide a number
	where you can receive SMS messages. Your number will never
	be disclosed to anyone else. Not even to your guild mates.
</p>

<p style="margin: 5px 0 0 0;">
	US users should enter their 10 digit mobile phone number without any
	parentheses or hyphens. (For example: "2065551234") International users
	should enter their full mobile number, preceded by their country code.
	You do not need to include an international dialing prefix. (For example, a
	French mobile number should be entered as: "33112345678")
</p>

<p style="margin: 5px 0 0 0; font-size: 0.85em;">
	Standard SMS rates from your provider will apply
	to any messages you receive through <strong>srs</strong>guild.
</p>

app/views/accounts/confirm.html.erb
<% title 'verify account' %>
<h2>Verify Account</h2>

<p>
	Please enter your email verification code below or click on the link in 
	the verification email we sent in order to verify your account.
</p>

<% form_tag(verify_manual_account_url, :method => :put) do %>
	<p>
		<label for="verification_value">Verification Code:</label><br />
		<input type="text" name="verification_value" size="10" />
	</p>

	<input type="submit" value="verify email" />
<% end %>

<br />
<br />


<p>
	If you did not receive a verification email, enter your email address 
	below and we will send you a new one!
</p>

<% form_tag(resend_confirmation_account_url, :method => :put) do %>
	<p>
		<label for="verify_email">Email Address:</label><br />
		<input type="text" name="verify_email" size="30" />
	</p>
	
	<input type="submit" value="send new verification message" />
<% end %>

app/views/accounts/forgot.html.erb
<% title 'password reminder' %>
<div id="Account_ForgotPassword">
	<h2>Forgot your password?</h2>
	
	<div class="grid_6 alpha">
		<p>
			Don't worry just enter your email address here and we'll send you 
			a link you can use to reset your password. Just make sure to keep 
			it in a safe place this time!
		</p>
		
		<p>
			If you don't remember the email address you signed up under, or
			if you are having any other problems with this password reset
			procedure, please <%= link_to('contact support', contact_url) %>.
		</p>
	</div>
	<div class="clear"></div>
	
	<% form_tag(remind_account_url, :method => :post, :class => 'srsform') do %>
		<div class="fieldrow">
			<label for="email">Your E-mail:</label>
			<div class="field"><%= text_field_tag('email', @email, {:class => 'text', :style => 'width: 300px;'}) %></div>
		</div>
		
		<div class="buttonrow">
			<% center_buttons do %>
				<button type="submit" class="button positive">
					<%= image_tag('icons/tick.png') %> send reminder
				</button>
				<% link_to(login_url, :class => "button negative") do %>
					<%= image_tag('icons/arrow_left.png') %> wait, I remember now!
				<% end %>
			<% end %>
		</div>
	<% end %>
</div>

app/views/accounts/new.html.erb
<% title 'sign up' %>
<h2>Account Sign Up</h2>
	
	<% if @guild %>
		<p style="text-align: center; padding-top: 10px;">
			<span style="font-size: 18px;">You are signing up to join the <strong><%=h @guild.name %></strong> guild.</span><br />
			(If this is not correct, please 
			<%= link_to('create an unaffiliated account', new_account_url(:subdomain => false)) %>
			instead.)
		</p>
	<% else %>
		<p class="grid_5 alpha">
			<strong>Looking for your guild?</strong><br />
			Sign up for a free account below. Once you have done that, you can 
			create your main character and then search for your guild. You will
			need to have your guild's "join code" in order to get everything set
			up. Check with your guild leader or another officer if you don't
			know the code.
		</p>
	
		<p class="grid_5 omega">
			<strong>Want to set up a new guild?</strong><br />
			Sign up for a free account below first, then you can create a new
			guild from the account management page. You can manage your guild
			free for the first 30 days, <del>after that you will need to pay with 
			a credit card to continue using our service.</del> <strong>(Guild 
			management is totally free during our beta!)</strong>
		</p>
	<% end %>
	
<div class="clear"></div>
<br />

<% form_for(@account, :url => account_path, :html => { :class => 'srsform'}) do %>
	<fieldset>
		<legend>New Account</legend>
		
		<div class="fieldrow">
			<label for="account[email]">Your E-mail:</label>
			<div class="field"><%= text_field(:account, :email, {:class => 'text', :style => 'width: 300px;'}) %></div>
		</div>

		<div class="fieldrow">
			<label for="account[password]">Choose a Password:</label>
			<div class="field"><%= password_field(:account, :password, {:class => 'text', :style => 'width: 120px;'}) %></div>
		</div>

		<div class="fieldrow">
			<label for="account[password_confirmation]">Confirm Password:</label>
			<div class="field"><%= password_field(:account, :password_confirmation, {:class => 'text', :style => 'width: 120px;'}) %></div>
		</div>

		<h3 style="padding-top: 20px;">10 Second User Agreement</h3>
		<p>By creating an account, you agree that:</p>
		<ul>
			<li>You will not use your account to advertise any commercial services.</li>
			<li>You will not harass, defame, berate, or enflame anyone through the means provided here.</li>
			<li>You are generally a good person.</li>
		</ul>
		
		<div class="fieldrow" id="terms_agree_box">
			<label for="terms_agree">I agree.</label>
			<input id="terms_agree" name="terms_agree" type="checkbox" />
		</div>
	</fieldset>
	
	<% if @character %>
		<fieldset>
			<legend>Main Character</legend>

			<% if flash[:armory_error] %>
				<p class="highlight" style="padding: 10px;">
					We couldn't find the information for that character in the WoW Armory.
					There are several possible reasons for this, but whatever the cause, 
					all you need to do is fill in a little bit more information about your
					character to continue.
				</p>
			<% end %>
			
			<%= render :partial => 'characters/form' %>
		</fieldset>
		
		<fieldset>
			<legend>Guild</legend>
			
			<div class="fieldrow">
				<label for="guild_join_code">Join Code:</label>
				<input id="guild_join_code" name="guild_join_code" type="text" class="text" style="width: 100px;" />
			</div>
		</fieldset>
	<% end %>

	<div class="buttonrow">
		<% center_buttons do %>
			<button type="submit" class="button positive" onclick="return verifyAgree();">
				<%= image_tag('icons/tick.png') %> let's go!
			</button>
		<% end %>
	</div>
<% end %>

<script type="text/javascript" charset="utf-8">
	function verifyAgree() {
		if (!$('terms_agree').checked) {
			$('terms_agree_box').pulsate();
			return false;
		}
		
		return true;
	}
</script>

app/views/accounts/new_password.html.erb
<% title 'choose a new password' %>
<div id="Account_NewPassword">
	<h2>Choose a New Password</h2>
	
	<div class="grid_6 alpha">
		<p>
			Hooray! You're only moments away from being in possession of a 
			shiny new password! Choose your new password below. Don't
			forget to write it down in a safe place this time!
		</p>
	</div>
	<div class="clear"></div>
	
	<% form_tag(reset_password_account_url, :method => :put, :class => 'srsform') do %>
		<%= hidden_field_tag('reset_code', @account.password_reset_value) %>
		
		<div class="fieldrow">
			<label for="new_password">New Password:</label>
			<div class="field">
				<%= password_field_tag('new_password', nil, :size => 24, :class => 'text') %>
			</div>
		</div>

		<div class="fieldrow">
			<label for="new_password_confirmation">Confirm Password:</label>
			<div class="field">
				<%= password_field_tag('new_password_confirmation', nil, :size => 24, :class => 'text') %>
			</div>
		</div>
		
		<div class="buttonrow">
			<% center_buttons do %>
				<button type="submit" class="button positive">
					<%= image_tag('icons/tick.png') %> reset password
				</button>
			<% end %>
		</div>
		
	<% end %>
</div>

app/views/accounts/show.html.erb
<% title 'my account' %>
<div id="AccountIndex">
	<h1 class="PageTitle">My Account</h1>

	<div class="SectionHeading">
		<h2>Main Character</h2>
	</div>
	
	<% if @main_char.blank? %>
		<p>You have not added any characters to your account yet, click the 'Add New Character' link below to get started. You should add your "main" character first.</p>
	<% else %>
		<ul class="CharacterList">
			<li class="<%= @main_char.character_class_css_name %>_border">
				<div class="CharIcon">
					<%= image_tag(@main_char.icon_path) %>
				</div>

				<div class="CharInfo">
					<h4 class="CharName"><%=h @main_char.name %></h4>
					<%= char_guild_name(@main_char) %>
					<p class="CharRaceClass">
						<%=h @main_char.race %> &ndash; <%=h @main_char.character_class %>
					</p>
				</div>
				
				<div class="CharControls">
					<% if @main_char.guild.nil? %>
						<%= link_to("Create New Guild", new_guild_url) %><br />
						<%= link_to('Join to Existing Guild', find_guild_account_character_url(@main_char)) %><br />
					<% else %>
						<%= link_to('Withdraw from Guild', withdraw_account_character_url(@main_char), :confirm => "Are you sure you want to withdraw all your characters from this guild?") %><br />
					<% end %>
					<%= link_to('Update from Armory', armory_update_account_character_url(@main_char)) %><br />
					<%# link_to('Remove from Account', character_url(:id => @main_char), :method => :delete, :confirm => "Are you sure you want to delete this character from your account?") %>
				</div>
			</li>
		</ul>
		
		<br />
		
		<% form_tag(account_character_url(@main_char), :method => :put, :class => 'srsform') do %>
			<fieldset>
				<legend>Character Settings</legend>
				<div class="fieldrow">
					<label for="main_char[event_role_preference]">Role Preference:</label>
					<div class="field"><%= select(:main_char, :event_role_preference, calendar_signup_role_options, :style => "width: 140px;") %></div>
				</div>
				
				<div class="fieldrow">
					<label for="main_char[raid_spec]">Raid Spec:</label>
					<div class="field">
						<% if @main_char.armory_spec1.blank? %>
							<p style="font-style: italic; margin: 0; padding-top: 4px;">Please <%= link_to('update from armory', armory_update_account_character_url(@main_char)) %> to enable this field.</p>
						<% else %>
							<%= select(:main_char, :raid_spec, @main_char.all_specs, :style => "width: 140px;") %>
						<% end %>
					</div>
				</div>
				
				<script type="text/javascript" charset="utf-8">
					// Help Tooltips
					new Tip($('main_char_raid_spec'), 'Only the talent trees currently trained on your character are shown.<br /> Click "Update from Armory" above if these are out of date.', {
						showOn: 'focus',
						hideOn: 'blur',
						hideOthers: true,
						fixed: true,
						stem: 'leftMiddle',
						hook: { target: 'rightMiddle', tip: 'leftMiddle' },
						offset: { x: 2, y: 0 },
						width: 'auto'
					});
				</script>
				
				<div class="buttonrow">
					<% center_buttons do %>
						<button type="submit" class="button positive">
							<%= image_tag('icons/tick.png') %> save character settings
						</button>
					<% end %>
				</div>
			</fieldset>
		<% end %>
	<% end %>
	
	<% unless @main_char.blank? %>
		<div class="SectionHeading">
			<h3>Alts</h3>
		</div>

		<% if @alts.blank? %>
			<p style="margin: 0;">You have not added any alternate characters yet, click the 'Add New Character' link below to add one.</p>
		<% else %>
			<table class="simple">
				<tr>
					<th>Name</th>
					<th style="width: 100px;">Class</th>
					<th style="width: 100px;">Race</th>
					<th style="width: 200px;"></th>
				</tr>

				<% @alts.each do |c| %>
					<tr>
						<td><%=h c.name %></td>
						<td><%= character_class_with_colorbox(c.character_class) %></td>
						<td><%=h c.race %></td>
						<td style="text-align: right;">
							<%= link_to('remove', account_character_url(c), :method => :delete, :confirm => "Are you sure you want to delete this character from your account?") %>
							&nbsp;&nbsp;
							<%= link_to('update', armory_update_account_character_url(c)) %>
							<%# link_to('promote to main', promote_account_character_url(c), :confirm => "Are you sure you want to make this character your new main character?") %>
						</td>
					</tr>
				<% end %>
			</table>
		<% end %>
	<% end %>
	
	<% center_buttons do %>
		<%= link_to("#{image_tag('icons/add.png')} add new character", new_account_character_url, :class => 'button') %>
	<% end %>
	
	<% if @_GUILD.nil? %>
		<% unless @main_char.blank? %>
			<p style="padding-top: 1em; font-size: 116%;">
				You have not joined your main character to a guild yet. You 
				can do that in the "My Characters" section above or you can 
				<%= link_to("set up a new guild", :controller => 'guild', :action => 'new') %>.
			</p>
		<% end %>
	<% end %>
	
	<br />
	<br />
	
	<% form_tag(account_url, :method => :put, :class => 'srsform') do %>
		<fieldset>
			<legend>Account Settings</legend>
			<div class="fieldrow">
				<label for="account[email]">Email Address:</label>
				<div class="field"><%= text_field(:account, :email, :size => 24, :class => 'text') %></div>
			</div>
			
			<div class="fieldrow">
				<label for="account[new_password]">Change Password:</label>
				<div class="field">
					<%= password_field(:account, :password, :size => 24, :class => 'text') %>
				</div>
			</div>

			<div class="fieldrow">
				<label for="account[password_confirmation]">Confirm Password:</label>
				<div class="field">
					<%= password_field(:account, :password_confirmation, :size => 24, :class => 'text') %>
				</div>
			</div>
			
			<div class="fieldrow">
				<label for="account[time_zone]">Your Time Zone:</label>
				<div class="field">
					<% unless @_GUILD.blank? or @_GUILD.guild_config.default_time_zone.blank? %>
						<%= time_zone_select(:account, :time_zone, ActiveSupport::TimeZone.us_zones, :default => @_GUILD.guild_config.default_time_zone, :include_blank => true) %>
					<% else %>
						<%= time_zone_select(:account, :time_zone, ActiveSupport::TimeZone.us_zones, :default => "Pacific Time (US & Canada)", :include_blank => true) %>
					<% end %>
				</div>
			</div>
			
			<div class="fieldrow">
				<label for="account[mobile_number]">Mobile Number:</label>
				<div class="field">
					<%= text_field(:account, :mobile_number, :size => 24, :class => 'text', :style => "float: left;") %>
					<%= image_tag('icons/phone.png', :style => "display: block; float: left; padding-top: 2px;") %>
					<script type="text/javascript" charset="utf-8">
						new Tip($('account_mobile_number'), '<%= escape_javascript(render(:partial => 'mobile_number_tooltip')) %>', {
							showOn: 'focus',
							hideOn: 'blur',
							hideOthers: true,
							fixed: true,
							stem: 'bottomLeft',
							hook: { target: 'topRight', tip: 'bottomLeft' },
							offset: { x: 5, y: 0 },
							width: 350
						});
					</script>
				</div>
			</div>
			
			<div class="buttonrow">
				<% center_buttons do %>
					<button type="submit" class="button positive">
						<%= image_tag('icons/tick.png') %> save settings
					</button>
				<% end %>
			</div>
		</fieldset>		
	<% end %>
</div>

app/views/accounts/success.html.erb
<% title 'account created' %>
<h2>Success!</h2>

<p>
	Your account was successfully created. (Huzzah!) You are already 
	logged in and can use your new account right away.
</p>
	
<p>
	In order to make sure you didn't type in your e-mail address wrong or 
	something, we're going to send a message to the address you provided in 
	the next few minutes. Inside that message will be a link you can click
	on to verify your address. If you don't do this sometime in the next week
	we'll have to disable your account, so it's best to do it right away so
	you don't forget! 
</p>

<p>
	(If you don't see the message in your inbox within 15
	minutes, check to see if your spam filter ate it. The message will come 
	from "support@srsguild.com".)
</p>
	
<h3>What Should I Do Next?</h3>

<% if @_GUILD %>
	<p>
		Well, you have already set up your main character, so you can either
		go straight to <%= link_to('your guild page', guild_url) %> or you 
		could hit up <%= link_to('your account page', account_url) %> to set
		some preferences.
	</p>
<% else %>
	<p>
		If you are a guild leader, you should <%= link_to('set up a new guild', new_guild_url) %> 
		but if you are joining an existing guild, go ahead and set up your  
		characters on <%= link_to('your account page', account_url) %>.
	</p>
<% end %>